# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_auto_20170423_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
